NAME = glut_projectile

RELEASE_TARGET = $(NAME)

TARGET = $(RELEASE_TARGET)

INCDIRS = -I../../library/include

LIBS = -lm -lGL -lGLU -lglut -lGLEW -lstdc++

CXX_OBJS = main.o

include ../Makefile.common
