NAME = glut_projectile

RELEASE_TARGET = $(NAME)

TARGETS = $(RELEASE_TARGET)

INCDIRS = -I../../library/include

LIBS = -lm -lGL -lGLU -lglut -lGLEW -lstdc++

OBJS_CXX = main.o

include ../Makefile.common
